import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "./components/Head";
import Footer from "./components/Footer";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
      <body className={inter.className}>
        <Head />
        {children}
        <Footer />
      </body>
      </ClerkProvider>
    </html>
  );
}
